[connections.snowflake]
account = "UHPTZJD-KQB34857"
user = "dyotan"
password = "W9B-xDekFG8epzu"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive=true
